"""Add date in modesl

Revision ID: 36cb1834a3f6
Revises: f96572a02783
Create Date: 2022-08-10 14:14:36.649938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cb1834a3f6'
down_revision = 'f96572a02783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
